spring:
  application:
    name: hw24-dic-bot

  grpc:
    client:
      channels:
        dic-channel:
          address: static://localhost:9090
          negotiation-type: TLS
          ssl:
            bundle: client-mtls
            secure: true

  ssl:
    bundle:
      jks:
        client-mtls:
          keystore:
            location: classpath:certificates/client.jks
            password: ${CERTIFICATE_PASSWORD}
            type: JKS
          key:
            password: ${CERTIFICATE_PASSWORD}
          truststore: # Contains trusted server certificates
            location: classpath:certificates/client-truststore.jks
            password: ${CERTIFICATE_PASSWORD}
            type: JKS

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    webhook-url: ${TELEGRAM_BOT_WEBHOOK_URL:your_telegram_bot_webhook_url_here}
